Repository Nexters/if-react-native, pull requests merged in 2021-04, with the labels that each got.

#2 [feat] 초기 화면 세팅
  App.js
  package.json
  screens/AddStoryScreen.js
  screens/AlbumScreen.js
  screens/EditStoryScreen.js
  screens/FeedScreen.js
  screens/LoginScreen.js
  screens/MainScreen.js
  screens/MyPageScreen.js
  yarn.lock
Labels: feature

#6 국가별 앨범 목록 화면 마크업
  .gitignore
  components/AlbumList/AlbumList.jsx
  components/AlbumList/AlbumListItem.jsx
  components/AlbumList/index.js
  components/AlbumNationList/AlbumNationItem.jsx
  components/AlbumNationList/AlbumNationList.jsx
  components/AlbumNationList/AlbumNationTitle.jsx
  components/AlbumNationList/index.js
  screens/AlbumScreen.js
  screens/AlbumScreen.jsx
  style/palette.js
Labels: Markup 🎨, feature

#13 [feat] 헤더 추가
  App.js
  assets/svg/album.js
  assets/svg/arrow.js
  assets/svg/feed.js
  assets/svg/index.js
  assets/svg/mypage.js
  components/Header/Header.jsx
  components/Header/IconItem.jsx
  components/Header/index.js
  components/SafeAreaViewLayout.jsx
  screens/AddStoryScreen.js
  screens/AlbumScreen.jsx
  screens/FeedScreen.js
  screens/LoginScreen.js
  screens/MainScreen.js
  screens/MyPageScreen.js
Labels: Markup 🎨, feature

#15 마이페이지 마크업
  .vscode/settings.json
  App.js
  assets/svg/apple.js
  assets/svg/arrow2.js
  assets/svg/cancel.js
  assets/svg/edit.js
  assets/svg/index.js
  assets/svg/kakao.js
  assets/svg/naver.js
  components/MyPage/AccountRow.jsx
  components/MyPage/ActionButton.jsx
  components/MyPage/UsernameRow.jsx
  components/MyPage/index.js
  screens/MyPageEditScreen.jsx
  screens/MyPageScreen.js
  screens/MyPageScreen.jsx
Labels: Markup 🎨

#18 스토리 추가 스크린 마크업
  assets/svg/index.js
  assets/svg/remove.js
  components/CountryText/CountryText.js
  components/CountryText/index.js
  components/Image/Image.js
  components/Image/ImageInput.js
  components/Image/ImageList.js
  components/Image/index.js
  components/Memo/Memo.js
  components/Memo/MemoInput.js
  components/Memo/index.js
  components/Place/Place.js
  components/Place/PlaceInput.js
  components/Place/index.js
  components/Title/Title.js
  components/Title/TitleInput.js
  components/Title/index.js
  components/common/FontText.js
  components/common/FontText/index.js
  components/common/FontTextInput.js
  components/common/index.js
  constants/types.js
  screens/AddStoryScreen.js
Labels: Markup 🎨
